[project]
name = "eleos"
description = "c++20 header-only library for exposing source engine interfaces"
version = "1.0.0"

[target.eleos]
type = "interface"
include-directories = ["include"]
compile-features = ["cxx_std_20"]